from trading.strategy.hybrid_validation import HybridValidationEvent


def event(
    *,
    status: str = "READY",
    reason_codes=None,
    theme_score: float = 80.0,
    membership_score: float = 0.8,
    theme_status: str = "ACTIVE",
    leader_type: str = "leader",
    entry_score: float = 80.0,
    rank_delta_5m: int = 0,
    breadth: float = 0.6,
    source_count: int = 2,
):
    codes = list(reason_codes or (["STRONG_ACTIVE_THEME"] if status == "READY" else []))
    return HybridValidationEvent(
        ts="2026-05-30T09:00:00",
        trade_date="2026-05-30",
        stock_code="000001",
        stock_name="MOCK-LEADER",
        candidate_source="condition",
        hybrid_status=status,
        hybrid_score=theme_score,
        hybrid_position_tier="normal_first_entry" if status == "READY" else "observe_only",
        hybrid_primary_reason=codes[0] if codes else "",
        hybrid_reason_codes=codes,
        theme_id="furiosa_ai",
        theme_name="퓨리오사AI",
        theme_status=theme_status,
        theme_score=theme_score,
        theme_rank=1,
        theme_rank_delta_5m=rank_delta_5m,
        theme_breadth=breadth,
        rising_count=4,
        total_count=5,
        leader_gap=1.2,
        top3_concentration=0.4,
        rank_in_theme=1,
        leader_type=leader_type,
        membership_score=membership_score,
        relation_type="investor",
        source_count=source_count,
        entry_timing_score=entry_score,
        chase_risk="false",
        market_score=90,
        risk_score=90,
        position_tier="normal_first_entry" if status == "READY" else "observe_only",
        details_json={"base_price": 100},
    )
