from __future__ import annotations

from enum import Enum
from typing import Any, Iterable

from trading.strategy.session import SESSION_BUCKET_UNKNOWN, session_bucket_at


REASON_DETAILS_FEATURE_VERSION = "reason_details_v1"
STRATEGY_FEATURE_VERSION = "observe_p1a_legacy_compare_v1"
COMPARISON_MODE_LEGACY_ONLY = "legacy_only"


class ReasonCode(str, Enum):
    DATA_INSUFFICIENT = "DATA_INSUFFICIENT"
    INDEX_WEAK = "INDEX_WEAK"
    THEME_WEAK = "THEME_WEAK"
    THEME_STRENGTH_C = "THEME_STRENGTH_C"
    THEME_LEADER_COLLAPSE = "THEME_LEADER_COLLAPSE"
    CHASE_RISK = "CHASE_RISK"
    WAIT_PULLBACK_CONFIRMATION = "WAIT_PULLBACK_CONFIRMATION"
    PULLBACK_TOO_DEEP = "PULLBACK_TOO_DEEP"
    LEADERSHIP_WEAK = "LEADERSHIP_WEAK"
    MARKET_INDEX_TEMPORARY_CAP = "MARKET_INDEX_TEMPORARY_CAP"
    DATA_INSUFFICIENT_CAP = "DATA_INSUFFICIENT_CAP"
    THEME_STRENGTH_C_CAP = "THEME_STRENGTH_C_CAP"
    THEME_PULLBACK_FINAL_CAP = "THEME_PULLBACK_FINAL_CAP"
    FINAL_BLOCK_CAP = "FINAL_BLOCK_CAP"
    STOCK_PULLBACK_WAIT_CAP = "STOCK_PULLBACK_WAIT_CAP"
    A_SIGNAL_KOSDAQ_WAIT_CAP = "A_SIGNAL_KOSDAQ_WAIT_CAP"
    LOW_SCORE_CAP = "LOW_SCORE_CAP"
    CHASE_RISK_CAP = "CHASE_RISK_CAP"
    SUPPORT_TOUCHED = "SUPPORT_TOUCHED"
    SUPPORT_RECLAIMED = "SUPPORT_RECLAIMED"
    VOLUME_REACCEL = "VOLUME_REACCEL"
    FAILED_LOW_BREAK_REBOUND = "FAILED_LOW_BREAK_REBOUND"
    TAKE_PROFIT_TARGET_REACHED = "TAKE_PROFIT_TARGET_REACHED"
    SUPPORT_LOSS_CONFIRMED = "SUPPORT_LOSS_CONFIRMED"
    TRAILING_STOP_CONFIRMED = "TRAILING_STOP_CONFIRMED"
    TIME_EXIT_MOMENTUM_FAILED = "TIME_EXIT_MOMENTUM_FAILED"
    DATA_INSUFFICIENT_EXIT_BASIS = "DATA_INSUFFICIENT_EXIT_BASIS"
    MARKET_BREADTH_WEAK = "MARKET_BREADTH_WEAK"
    INDEX_SLOPE_WEAK = "INDEX_SLOPE_WEAK"
    OPEN_GAP_RISK = "OPEN_GAP_RISK"
    THEME_SYNC_WEAK = "THEME_SYNC_WEAK"
    LEADER_FOLLOWER_GAP = "LEADER_FOLLOWER_GAP"
    LEADER_REPLACED = "LEADER_REPLACED"
    LATE_CHASE = "LATE_CHASE"
    LATE_CHASE_TEMP_WAIT = "LATE_CHASE_TEMP_WAIT"
    LATE_CHASE_WARNING = "LATE_CHASE_WARNING"
    LATE_CHASE_RECOVERY_PENDING = "LATE_CHASE_RECOVERY_PENDING"
    RISK_SOFT_BLOCK_TEMP_WAIT = "RISK_SOFT_BLOCK_TEMP_WAIT"
    CANDIDATE_MARKET_WEAK = "CANDIDATE_MARKET_WEAK"
    CANDIDATE_MARKET_RISK_OFF = "CANDIDATE_MARKET_RISK_OFF"
    KOSDAQ_MARKET_WEAK = "KOSDAQ_MARKET_WEAK"
    KOSDAQ_MARKET_RISK_OFF = "KOSDAQ_MARKET_RISK_OFF"
    KOSPI_MARKET_WEAK = "KOSPI_MARKET_WEAK"
    KOSPI_MARKET_RISK_OFF = "KOSPI_MARKET_RISK_OFF"
    GLOBAL_MARKET_RISK_OFF = "GLOBAL_MARKET_RISK_OFF"
    MARKET_CLASSIFICATION_MISSING = "MARKET_CLASSIFICATION_MISSING"
    MARKET_CLASSIFICATION_FALLBACK_STRICT = "MARKET_CLASSIFICATION_FALLBACK_STRICT"
    MARKET_CLASSIFICATION_HEURISTIC_USED = "MARKET_CLASSIFICATION_HEURISTIC_USED"
    MARKET_SIDE_DATA_INSUFFICIENT = "MARKET_SIDE_DATA_INSUFFICIENT"
    SIDE_BREADTH_FALLBACK_GLOBAL = "SIDE_BREADTH_FALLBACK_GLOBAL"
    KOSPI_SIDE_BREADTH_WEAK = "KOSPI_SIDE_BREADTH_WEAK"
    KOSDAQ_SIDE_BREADTH_WEAK = "KOSDAQ_SIDE_BREADTH_WEAK"
    KOSPI_SIDE_BREADTH_RISK_OFF = "KOSPI_SIDE_BREADTH_RISK_OFF"
    KOSDAQ_SIDE_BREADTH_RISK_OFF = "KOSDAQ_SIDE_BREADTH_RISK_OFF"
    KOSPI_SIDE_BREADTH_EXPANSION = "KOSPI_SIDE_BREADTH_EXPANSION"
    KOSDAQ_SIDE_BREADTH_EXPANSION = "KOSDAQ_SIDE_BREADTH_EXPANSION"
    KOSPI_SIDE_BREADTH_SELECTIVE = "KOSPI_SIDE_BREADTH_SELECTIVE"
    KOSDAQ_SIDE_BREADTH_SELECTIVE = "KOSDAQ_SIDE_BREADTH_SELECTIVE"
    KOSPI_SIDE_BREADTH_CHOPPY = "KOSPI_SIDE_BREADTH_CHOPPY"
    KOSDAQ_SIDE_BREADTH_CHOPPY = "KOSDAQ_SIDE_BREADTH_CHOPPY"
    SIDE_BREADTH_NOT_READY = "SIDE_BREADTH_NOT_READY"
    SIDE_BREADTH_SAMPLE_TOO_SMALL = "SIDE_BREADTH_SAMPLE_TOO_SMALL"
    SIDE_BREADTH_VALID_QUOTE_RATIO_LOW = "SIDE_BREADTH_VALID_QUOTE_RATIO_LOW"
    SIDE_BREADTH_FALLBACK_INDEX_RETURN = "SIDE_BREADTH_FALLBACK_INDEX_RETURN"
    SIDE_BREADTH_FALLBACK_WATCH_UNIVERSE = "SIDE_BREADTH_FALLBACK_WATCH_UNIVERSE"
    SIDE_BREADTH_FALLBACK_CANDIDATE_UNIVERSE = "SIDE_BREADTH_FALLBACK_CANDIDATE_UNIVERSE"
    SIDE_BREADTH_WEAK_INDEX_OK = "SIDE_BREADTH_WEAK_INDEX_OK"
    INDEX_WEAK_BREADTH_OK = "INDEX_WEAK_BREADTH_OK"
    SIDE_BREADTH_SOURCE_REALTIME_UNIVERSE = "SIDE_BREADTH_SOURCE_REALTIME_UNIVERSE"
    SIDE_BREADTH_SOURCE_SYMBOL_UNIVERSE = "SIDE_BREADTH_SOURCE_SYMBOL_UNIVERSE"
    SIDE_BREADTH_SOURCE_WATCH_UNIVERSE = "SIDE_BREADTH_SOURCE_WATCH_UNIVERSE"
    SIDE_BREADTH_SOURCE_CANDIDATE_UNIVERSE = "SIDE_BREADTH_SOURCE_CANDIDATE_UNIVERSE"
    SIDE_BREADTH_SOURCE_CONFLICT = "SIDE_BREADTH_SOURCE_CONFLICT"
    SIDE_BREADTH_LOW_TRUST = "SIDE_BREADTH_LOW_TRUST"
    SIDE_BREADTH_DIAGNOSTIC_ONLY = "SIDE_BREADTH_DIAGNOSTIC_ONLY"
    MARKET_WEAK_CONFIRMATION_PENDING = "MARKET_WEAK_CONFIRMATION_PENDING"
    MARKET_RISK_OFF_CONFIRMATION_PENDING = "MARKET_RISK_OFF_CONFIRMATION_PENDING"
    CANDIDATE_MARKET_WEAK_UNCONFIRMED = "CANDIDATE_MARKET_WEAK_UNCONFIRMED"
    CANDIDATE_MARKET_RISK_OFF_UNCONFIRMED = "CANDIDATE_MARKET_RISK_OFF_UNCONFIRMED"
    MARKET_WEAK_CONFIRMED = "MARKET_WEAK_CONFIRMED"
    MARKET_RISK_OFF_CONFIRMED = "MARKET_RISK_OFF_CONFIRMED"
    WAIT_MARKET_CONFIRMATION_PENDING = "WAIT_MARKET_CONFIRMATION_PENDING"
    WAIT_CANDIDATE_MARKET_WEAK = "WAIT_CANDIDATE_MARKET_WEAK"
    WAIT_CANDIDATE_MARKET_RISK_OFF = "WAIT_CANDIDATE_MARKET_RISK_OFF"
    MARKET_RECOVERY_CONFIRMATION_PENDING = "MARKET_RECOVERY_CONFIRMATION_PENDING"
    WAIT_MARKET_RECOVERY_PENDING = "WAIT_MARKET_RECOVERY_PENDING"
    MARKET_WAIT_HYSTERESIS_HOLD = "MARKET_WAIT_HYSTERESIS_HOLD"
    MARKET_WAIT_RECOVERED = "MARKET_WAIT_RECOVERED"
    MARKET_RECOVERY_CONFIRMED = "MARKET_RECOVERY_CONFIRMED"
    MARKET_WAIT_STATE_RESET = "MARKET_WAIT_STATE_RESET"
    MARKET_WAIT_REPORT_ONLY = "MARKET_WAIT_REPORT_ONLY"
    MARKET_CONFIRMATION_STATE_RESTORED = "MARKET_CONFIRMATION_STATE_RESTORED"
    MARKET_CONFIRMATION_STATE_RESTORE_FAILED = "MARKET_CONFIRMATION_STATE_RESTORE_FAILED"
    MARKET_CONFIRMATION_STATE_PERSISTED = "MARKET_CONFIRMATION_STATE_PERSISTED"
    MARKET_CONFIRMATION_STATE_PERSIST_FAILED = "MARKET_CONFIRMATION_STATE_PERSIST_FAILED"
    MARKET_CONFIRMATION_STATE_DB_ERROR = "MARKET_CONFIRMATION_STATE_DB_ERROR"
    MARKET_CONFIRMATION_STATE_STALE = "MARKET_CONFIRMATION_STATE_STALE"
    MARKET_CONFIRMATION_STATE_EXPIRED = "MARKET_CONFIRMATION_STATE_EXPIRED"
    MARKET_CONFIRMATION_STATE_VERSION_MISMATCH = "MARKET_CONFIRMATION_STATE_VERSION_MISMATCH"
    MARKET_CONFIRMATION_STATE_DATE_MISMATCH = "MARKET_CONFIRMATION_STATE_DATE_MISMATCH"
    MARKET_CONFIRMATION_STATE_RESET = "MARKET_CONFIRMATION_STATE_RESET"
    MARKET_CONFIRMATION_STATE_MEMORY_FALLBACK = "MARKET_CONFIRMATION_STATE_MEMORY_FALLBACK"
    MARKET_CONFIRMATION_STATE_CONSERVATIVE_FALLBACK = "MARKET_CONFIRMATION_STATE_CONSERVATIVE_FALLBACK"
    MARKET_CONFIRMATION_TRANSITION_LOGGED = "MARKET_CONFIRMATION_TRANSITION_LOGGED"
    MARKET_CONFIRMATION_TRANSITION_LOG_FAILED = "MARKET_CONFIRMATION_TRANSITION_LOG_FAILED"
    MARKET_CONFIRMATION_STATE_RESTORE_SKIPPED = "MARKET_CONFIRMATION_STATE_RESTORE_SKIPPED"
    MARKET_CONFIRMATION_STATE_SESSION_MISMATCH = "MARKET_CONFIRMATION_STATE_SESSION_MISMATCH"
    MARKET_CONFIRMATION_STATE_SESSION_CLOSED = "MARKET_CONFIRMATION_STATE_SESSION_CLOSED"
    MARKET_CONFIRMATION_STATE_HOLIDAY = "MARKET_CONFIRMATION_STATE_HOLIDAY"
    MARKET_CONFIRMATION_STATE_SCHEDULE_UNKNOWN = "MARKET_CONFIRMATION_STATE_SCHEDULE_UNKNOWN"
    MARKET_CONFIRMATION_STATE_RESTORE_NOT_ALLOWED = "MARKET_CONFIRMATION_STATE_RESTORE_NOT_ALLOWED"
    MARKET_CONFIRMATION_STATE_RESET_ON_SESSION_CHANGE = "MARKET_CONFIRMATION_STATE_RESET_ON_SESSION_CHANGE"
    MARKET_CONFIRMATION_STATE_RESET_ON_TRADE_DATE_CHANGE = "MARKET_CONFIRMATION_STATE_RESET_ON_TRADE_DATE_CHANGE"
    MARKET_CONFIRMATION_STATE_RESET_ON_MARKET_CLOSE = "MARKET_CONFIRMATION_STATE_RESET_ON_MARKET_CLOSE"
    MARKET_CONFIRMATION_STATE_FORCE_RESET = "MARKET_CONFIRMATION_STATE_FORCE_RESET"
    MARKET_CONFIRMATION_STATE_ROW_INVALID = "MARKET_CONFIRMATION_STATE_ROW_INVALID"
    MARKET_CONFIRMATION_STATE_RESTORE_AGE_EXCEEDED = "MARKET_CONFIRMATION_STATE_RESTORE_AGE_EXCEEDED"
    MARKET_SESSION_BOUNDARY_DETECTED = "MARKET_SESSION_BOUNDARY_DETECTED"
    MARKET_SESSION_REGULAR_OPEN = "MARKET_SESSION_REGULAR_OPEN"
    MARKET_SESSION_REGULAR_CLOSE = "MARKET_SESSION_REGULAR_CLOSE"
    MARKET_SESSION_PRE_OPEN = "MARKET_SESSION_PRE_OPEN"
    MARKET_SESSION_POST_CLOSE = "MARKET_SESSION_POST_CLOSE"
    MARKET_SESSION_CLOSED = "MARKET_SESSION_CLOSED"
    LIVE_PATH_UNCHANGED = "LIVE_PATH_UNCHANGED"
    LIVE_ORDER_GUARD_NOT_BYPASSED = "LIVE_ORDER_GUARD_NOT_BYPASSED"
    LIVE_ORDER_DISABLED_CONFIRMED = "LIVE_ORDER_DISABLED_CONFIRMED"
    DISPLAY_STATUS_NORMALIZED = "DISPLAY_STATUS_NORMALIZED"
    MARKET_GATE_REVIEW_ROW_CREATED = "MARKET_GATE_REVIEW_ROW_CREATED"
    MARKET_GATE_REVIEW_ATTRIBUTION_LOW_CONFIDENCE = "MARKET_GATE_REVIEW_ATTRIBUTION_LOW_CONFIDENCE"
    MARKET_GATE_REVIEW_PRICE_DATA_MISSING = "MARKET_GATE_REVIEW_PRICE_DATA_MISSING"
    MARKET_GATE_REVIEW_FALSE_BLOCK_CANDIDATE = "MARKET_GATE_REVIEW_FALSE_BLOCK_CANDIDATE"
    MARKET_GATE_REVIEW_RESTORED_STATE_ANALYZED = "MARKET_GATE_REVIEW_RESTORED_STATE_ANALYZED"
    MARKET_GATE_REVIEW_SESSION_RESET_ANALYZED = "MARKET_GATE_REVIEW_SESSION_RESET_ANALYZED"
    ACCOUNT_GUARD_PASSED_SIMULATION = "ACCOUNT_GUARD_PASSED_SIMULATION"
    ACCOUNT_GUARD_FAILED_REAL_ACCOUNT = "ACCOUNT_GUARD_FAILED_REAL_ACCOUNT"
    ACCOUNT_GUARD_FAILED_UNKNOWN_ACCOUNT_MODE = "ACCOUNT_GUARD_FAILED_UNKNOWN_ACCOUNT_MODE"
    ACCOUNT_GUARD_FAILED_ACCOUNT_NOT_ALLOWLISTED = "ACCOUNT_GUARD_FAILED_ACCOUNT_NOT_ALLOWLISTED"
    ACCOUNT_GUARD_FAILED_SERVER_MODE_UNKNOWN = "ACCOUNT_GUARD_FAILED_SERVER_MODE_UNKNOWN"
    LIVE_REAL_ORDER_BLOCKED = "LIVE_REAL_ORDER_BLOCKED"
    LIVE_SIM_ORDER_ALLOWED = "LIVE_SIM_ORDER_ALLOWED"
    LIVE_SIM_ORDER_BLOCKED_ACCOUNT_GUARD = "LIVE_SIM_ORDER_BLOCKED_ACCOUNT_GUARD"
    LIVE_SIM_FIRST_LEG_ONLY = "LIVE_SIM_FIRST_LEG_ONLY"
    SECOND_THIRD_LEG_BLOCKED_BEFORE_FIRST_FILL = "SECOND_THIRD_LEG_BLOCKED_BEFORE_FIRST_FILL"
    DUPLICATE_FIRST_LEG_ORDER_BLOCKED = "DUPLICATE_FIRST_LEG_ORDER_BLOCKED"
    LIVE_SIM_ORDER_COOLDOWN_ACTIVE = "LIVE_SIM_ORDER_COOLDOWN_ACTIVE"
    LIVE_SIM_PARTIAL_FILL_TRACKED = "LIVE_SIM_PARTIAL_FILL_TRACKED"
    LIVE_SIM_UNFILLED_ORDER_TRACKED = "LIVE_SIM_UNFILLED_ORDER_TRACKED"
    ORDER_IDEMPOTENCY_KEY_CREATED = "ORDER_IDEMPOTENCY_KEY_CREATED"
    ORDER_DUPLICATE_BLOCKED = "ORDER_DUPLICATE_BLOCKED"
    ORDER_UNKNOWN_SUBMIT_REQUIRES_RECONCILE = "ORDER_UNKNOWN_SUBMIT_REQUIRES_RECONCILE"
    ORDER_RESTART_RESTORED_PENDING = "ORDER_RESTART_RESTORED_PENDING"
    ORDER_RECONCILED_FROM_KIWOOM = "ORDER_RECONCILED_FROM_KIWOOM"
    EXIT_GUARD_REQUIRED = "EXIT_GUARD_REQUIRED"
    EXIT_GUARD_NOT_READY_BUY_BLOCKED = "EXIT_GUARD_NOT_READY_BUY_BLOCKED"
    LIVE_SIM_STOP_LOSS_TRIGGERED = "LIVE_SIM_STOP_LOSS_TRIGGERED"
    LIVE_SIM_TAKE_PROFIT_TRIGGERED = "LIVE_SIM_TAKE_PROFIT_TRIGGERED"
    LIVE_SIM_MAX_HOLD_EXIT_TRIGGERED = "LIVE_SIM_MAX_HOLD_EXIT_TRIGGERED"
    LIVE_SIM_MARKET_CLOSE_LIQUIDATION_TRIGGERED = "LIVE_SIM_MARKET_CLOSE_LIQUIDATION_TRIGGERED"
    LIVE_SIM_EXIT_ORDER_SUBMITTED = "LIVE_SIM_EXIT_ORDER_SUBMITTED"
    LIVE_SIM_EXIT_ORDER_BLOCKED = "LIVE_SIM_EXIT_ORDER_BLOCKED"
    LIVE_SIM_ORDER_REJECTED = "LIVE_SIM_ORDER_REJECTED"
    LIVE_SIM_ORDER_UNFILLED_TIMEOUT = "LIVE_SIM_ORDER_UNFILLED_TIMEOUT"
    LIVE_SIM_ORDER_CANCEL_REQUESTED = "LIVE_SIM_ORDER_CANCEL_REQUESTED"
    LIVE_SIM_ORDER_CANCELLED = "LIVE_SIM_ORDER_CANCELLED"
    LIVE_SIM_ORDER_CANCEL_FAILED = "LIVE_SIM_ORDER_CANCEL_FAILED"
    LIVE_SIM_ORDER_RECONCILE_REQUIRED = "LIVE_SIM_ORDER_RECONCILE_REQUIRED"
    LIVE_SIM_ORDER_PARTIAL_REMAIN_CANCELLED = "LIVE_SIM_ORDER_PARTIAL_REMAIN_CANCELLED"
    LIVE_SIM_KILL_SWITCH_ACTIVE = "LIVE_SIM_KILL_SWITCH_ACTIVE"
    LIVE_SIM_DAILY_LOSS_LIMIT_HIT = "LIVE_SIM_DAILY_LOSS_LIMIT_HIT"
    LIVE_SIM_MAX_ORDERS_HIT = "LIVE_SIM_MAX_ORDERS_HIT"
    LIVE_SIM_MAX_REJECTS_HIT = "LIVE_SIM_MAX_REJECTS_HIT"
    LIVE_SIM_BROKER_DISCONNECTED = "LIVE_SIM_BROKER_DISCONNECTED"
    LIVE_SIM_RECONCILE_FAILURE_LIMIT_HIT = "LIVE_SIM_RECONCILE_FAILURE_LIMIT_HIT"
    WAIT_MARKET_RECOVERY = "WAIT_MARKET_RECOVERY"
    NOT_ELIGIBLE_MARKET = "NOT_ELIGIBLE_MARKET"
    FILL_LIQUIDITY_WEAK = "FILL_LIQUIDITY_WEAK"
    SPREAD_TOO_WIDE = "SPREAD_TOO_WIDE"
    SESSION_PROFILE_RESTRICTED = "SESSION_PROFILE_RESTRICTED"
    INPUT_MISSING = "INPUT_MISSING"
    BREADTH_SCOPE_LIMITED = "BREADTH_SCOPE_LIMITED"
    FILL_INPUT_INSUFFICIENT = "FILL_INPUT_INSUFFICIENT"
    SETTINGS_KEY_MISSING = "SETTINGS_KEY_MISSING"
    SOFT_BLOCK_ONLY = "SOFT_BLOCK_ONLY"


P1_REASON_CODES = {
    ReasonCode.MARKET_BREADTH_WEAK.value,
    ReasonCode.INDEX_SLOPE_WEAK.value,
    ReasonCode.OPEN_GAP_RISK.value,
    ReasonCode.THEME_SYNC_WEAK.value,
    ReasonCode.LEADER_FOLLOWER_GAP.value,
    ReasonCode.LEADER_REPLACED.value,
    ReasonCode.LATE_CHASE.value,
    ReasonCode.LATE_CHASE_TEMP_WAIT.value,
    ReasonCode.LATE_CHASE_WARNING.value,
    ReasonCode.LATE_CHASE_RECOVERY_PENDING.value,
    ReasonCode.RISK_SOFT_BLOCK_TEMP_WAIT.value,
    ReasonCode.CANDIDATE_MARKET_WEAK.value,
    ReasonCode.CANDIDATE_MARKET_RISK_OFF.value,
    ReasonCode.KOSDAQ_MARKET_WEAK.value,
    ReasonCode.KOSDAQ_MARKET_RISK_OFF.value,
    ReasonCode.KOSPI_MARKET_WEAK.value,
    ReasonCode.KOSPI_MARKET_RISK_OFF.value,
    ReasonCode.GLOBAL_MARKET_RISK_OFF.value,
    ReasonCode.MARKET_CLASSIFICATION_MISSING.value,
    ReasonCode.MARKET_CLASSIFICATION_FALLBACK_STRICT.value,
    ReasonCode.MARKET_CLASSIFICATION_HEURISTIC_USED.value,
    ReasonCode.MARKET_SIDE_DATA_INSUFFICIENT.value,
    ReasonCode.SIDE_BREADTH_FALLBACK_GLOBAL.value,
    ReasonCode.KOSPI_SIDE_BREADTH_WEAK.value,
    ReasonCode.KOSDAQ_SIDE_BREADTH_WEAK.value,
    ReasonCode.KOSPI_SIDE_BREADTH_RISK_OFF.value,
    ReasonCode.KOSDAQ_SIDE_BREADTH_RISK_OFF.value,
    ReasonCode.KOSPI_SIDE_BREADTH_EXPANSION.value,
    ReasonCode.KOSDAQ_SIDE_BREADTH_EXPANSION.value,
    ReasonCode.KOSPI_SIDE_BREADTH_SELECTIVE.value,
    ReasonCode.KOSDAQ_SIDE_BREADTH_SELECTIVE.value,
    ReasonCode.KOSPI_SIDE_BREADTH_CHOPPY.value,
    ReasonCode.KOSDAQ_SIDE_BREADTH_CHOPPY.value,
    ReasonCode.SIDE_BREADTH_NOT_READY.value,
    ReasonCode.SIDE_BREADTH_SAMPLE_TOO_SMALL.value,
    ReasonCode.SIDE_BREADTH_VALID_QUOTE_RATIO_LOW.value,
    ReasonCode.SIDE_BREADTH_FALLBACK_INDEX_RETURN.value,
    ReasonCode.SIDE_BREADTH_FALLBACK_WATCH_UNIVERSE.value,
    ReasonCode.SIDE_BREADTH_FALLBACK_CANDIDATE_UNIVERSE.value,
    ReasonCode.SIDE_BREADTH_WEAK_INDEX_OK.value,
    ReasonCode.INDEX_WEAK_BREADTH_OK.value,
    ReasonCode.SIDE_BREADTH_SOURCE_REALTIME_UNIVERSE.value,
    ReasonCode.SIDE_BREADTH_SOURCE_SYMBOL_UNIVERSE.value,
    ReasonCode.SIDE_BREADTH_SOURCE_WATCH_UNIVERSE.value,
    ReasonCode.SIDE_BREADTH_SOURCE_CANDIDATE_UNIVERSE.value,
    ReasonCode.SIDE_BREADTH_SOURCE_CONFLICT.value,
    ReasonCode.SIDE_BREADTH_LOW_TRUST.value,
    ReasonCode.SIDE_BREADTH_DIAGNOSTIC_ONLY.value,
    ReasonCode.MARKET_WEAK_CONFIRMATION_PENDING.value,
    ReasonCode.MARKET_RISK_OFF_CONFIRMATION_PENDING.value,
    ReasonCode.CANDIDATE_MARKET_WEAK_UNCONFIRMED.value,
    ReasonCode.CANDIDATE_MARKET_RISK_OFF_UNCONFIRMED.value,
    ReasonCode.MARKET_WEAK_CONFIRMED.value,
    ReasonCode.MARKET_RISK_OFF_CONFIRMED.value,
    ReasonCode.WAIT_MARKET_CONFIRMATION_PENDING.value,
    ReasonCode.WAIT_CANDIDATE_MARKET_WEAK.value,
    ReasonCode.WAIT_CANDIDATE_MARKET_RISK_OFF.value,
    ReasonCode.MARKET_RECOVERY_CONFIRMATION_PENDING.value,
    ReasonCode.WAIT_MARKET_RECOVERY_PENDING.value,
    ReasonCode.MARKET_WAIT_HYSTERESIS_HOLD.value,
    ReasonCode.MARKET_WAIT_RECOVERED.value,
    ReasonCode.MARKET_RECOVERY_CONFIRMED.value,
    ReasonCode.MARKET_WAIT_STATE_RESET.value,
    ReasonCode.MARKET_WAIT_REPORT_ONLY.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_RESTORED.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_RESTORE_FAILED.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_PERSISTED.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_PERSIST_FAILED.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_DB_ERROR.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_STALE.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_EXPIRED.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_VERSION_MISMATCH.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_DATE_MISMATCH.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_RESET.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_MEMORY_FALLBACK.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_CONSERVATIVE_FALLBACK.value,
    ReasonCode.MARKET_CONFIRMATION_TRANSITION_LOGGED.value,
    ReasonCode.MARKET_CONFIRMATION_TRANSITION_LOG_FAILED.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_RESTORE_SKIPPED.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_SESSION_MISMATCH.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_SESSION_CLOSED.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_HOLIDAY.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_SCHEDULE_UNKNOWN.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_RESTORE_NOT_ALLOWED.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_RESET_ON_SESSION_CHANGE.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_RESET_ON_TRADE_DATE_CHANGE.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_RESET_ON_MARKET_CLOSE.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_FORCE_RESET.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_ROW_INVALID.value,
    ReasonCode.MARKET_CONFIRMATION_STATE_RESTORE_AGE_EXCEEDED.value,
    ReasonCode.MARKET_SESSION_BOUNDARY_DETECTED.value,
    ReasonCode.MARKET_SESSION_REGULAR_OPEN.value,
    ReasonCode.MARKET_SESSION_REGULAR_CLOSE.value,
    ReasonCode.MARKET_SESSION_PRE_OPEN.value,
    ReasonCode.MARKET_SESSION_POST_CLOSE.value,
    ReasonCode.MARKET_SESSION_CLOSED.value,
    ReasonCode.LIVE_PATH_UNCHANGED.value,
    ReasonCode.LIVE_ORDER_GUARD_NOT_BYPASSED.value,
    ReasonCode.LIVE_ORDER_DISABLED_CONFIRMED.value,
    ReasonCode.DISPLAY_STATUS_NORMALIZED.value,
    ReasonCode.MARKET_GATE_REVIEW_ROW_CREATED.value,
    ReasonCode.MARKET_GATE_REVIEW_ATTRIBUTION_LOW_CONFIDENCE.value,
    ReasonCode.MARKET_GATE_REVIEW_PRICE_DATA_MISSING.value,
    ReasonCode.MARKET_GATE_REVIEW_FALSE_BLOCK_CANDIDATE.value,
    ReasonCode.MARKET_GATE_REVIEW_RESTORED_STATE_ANALYZED.value,
    ReasonCode.MARKET_GATE_REVIEW_SESSION_RESET_ANALYZED.value,
    ReasonCode.ACCOUNT_GUARD_PASSED_SIMULATION.value,
    ReasonCode.ACCOUNT_GUARD_FAILED_REAL_ACCOUNT.value,
    ReasonCode.ACCOUNT_GUARD_FAILED_UNKNOWN_ACCOUNT_MODE.value,
    ReasonCode.ACCOUNT_GUARD_FAILED_ACCOUNT_NOT_ALLOWLISTED.value,
    ReasonCode.ACCOUNT_GUARD_FAILED_SERVER_MODE_UNKNOWN.value,
    ReasonCode.LIVE_REAL_ORDER_BLOCKED.value,
    ReasonCode.LIVE_SIM_ORDER_ALLOWED.value,
    ReasonCode.LIVE_SIM_ORDER_BLOCKED_ACCOUNT_GUARD.value,
    ReasonCode.LIVE_SIM_FIRST_LEG_ONLY.value,
    ReasonCode.SECOND_THIRD_LEG_BLOCKED_BEFORE_FIRST_FILL.value,
    ReasonCode.DUPLICATE_FIRST_LEG_ORDER_BLOCKED.value,
    ReasonCode.LIVE_SIM_ORDER_COOLDOWN_ACTIVE.value,
    ReasonCode.LIVE_SIM_PARTIAL_FILL_TRACKED.value,
    ReasonCode.LIVE_SIM_UNFILLED_ORDER_TRACKED.value,
    ReasonCode.ORDER_IDEMPOTENCY_KEY_CREATED.value,
    ReasonCode.ORDER_DUPLICATE_BLOCKED.value,
    ReasonCode.ORDER_UNKNOWN_SUBMIT_REQUIRES_RECONCILE.value,
    ReasonCode.ORDER_RESTART_RESTORED_PENDING.value,
    ReasonCode.ORDER_RECONCILED_FROM_KIWOOM.value,
    ReasonCode.EXIT_GUARD_REQUIRED.value,
    ReasonCode.EXIT_GUARD_NOT_READY_BUY_BLOCKED.value,
    ReasonCode.LIVE_SIM_STOP_LOSS_TRIGGERED.value,
    ReasonCode.LIVE_SIM_TAKE_PROFIT_TRIGGERED.value,
    ReasonCode.LIVE_SIM_MAX_HOLD_EXIT_TRIGGERED.value,
    ReasonCode.LIVE_SIM_MARKET_CLOSE_LIQUIDATION_TRIGGERED.value,
    ReasonCode.LIVE_SIM_EXIT_ORDER_SUBMITTED.value,
    ReasonCode.LIVE_SIM_EXIT_ORDER_BLOCKED.value,
    ReasonCode.LIVE_SIM_ORDER_REJECTED.value,
    ReasonCode.LIVE_SIM_ORDER_UNFILLED_TIMEOUT.value,
    ReasonCode.LIVE_SIM_ORDER_CANCEL_REQUESTED.value,
    ReasonCode.LIVE_SIM_ORDER_CANCELLED.value,
    ReasonCode.LIVE_SIM_ORDER_CANCEL_FAILED.value,
    ReasonCode.LIVE_SIM_ORDER_RECONCILE_REQUIRED.value,
    ReasonCode.LIVE_SIM_ORDER_PARTIAL_REMAIN_CANCELLED.value,
    ReasonCode.LIVE_SIM_KILL_SWITCH_ACTIVE.value,
    ReasonCode.LIVE_SIM_DAILY_LOSS_LIMIT_HIT.value,
    ReasonCode.LIVE_SIM_MAX_ORDERS_HIT.value,
    ReasonCode.LIVE_SIM_MAX_REJECTS_HIT.value,
    ReasonCode.LIVE_SIM_BROKER_DISCONNECTED.value,
    ReasonCode.LIVE_SIM_RECONCILE_FAILURE_LIMIT_HIT.value,
    ReasonCode.WAIT_MARKET_RECOVERY.value,
    ReasonCode.NOT_ELIGIBLE_MARKET.value,
    ReasonCode.FILL_LIQUIDITY_WEAK.value,
    ReasonCode.SPREAD_TOO_WIDE.value,
    ReasonCode.SESSION_PROFILE_RESTRICTED.value,
    ReasonCode.INPUT_MISSING.value,
    ReasonCode.BREADTH_SCOPE_LIMITED.value,
    ReasonCode.FILL_INPUT_INSUFFICIENT.value,
    ReasonCode.SETTINGS_KEY_MISSING.value,
    ReasonCode.SOFT_BLOCK_ONLY.value,
}


def normalize_reason_code(value: Any) -> str:
    if isinstance(value, ReasonCode):
        return value.value
    return str(value or "").strip()


def normalize_reason_codes(values: Iterable[Any] | None) -> list[str]:
    result: list[str] = []
    for value in values or []:
        text = normalize_reason_code(value)
        if text and text not in result:
            result.append(text)
    return result


def standardize_details(
    details: dict | None,
    reason_codes: Iterable[Any] | None = None,
    *,
    passed: Any = None,
    score: Any = None,
    created_at: Any = None,
    session_bucket: str | None = None,
    comparison_mode: str = COMPARISON_MODE_LEGACY_ONLY,
    legacy_result: Any = None,
    new_result: Any = None,
    legacy_score: Any = None,
    new_score: Any = None,
) -> dict:
    normalized = dict(details or {})
    codes = normalize_reason_codes(reason_codes)
    existing_primary = normalize_reason_code(normalized.get("primary_reason_code"))
    primary = existing_primary or (codes[0] if codes else "")
    secondary = normalize_reason_codes(
        list(normalized.get("secondary_reason_codes") or [])
        + [code for code in codes if code != primary]
    )

    normalized.setdefault("feature_version", REASON_DETAILS_FEATURE_VERSION)
    normalized.setdefault("strategy_feature_version", STRATEGY_FEATURE_VERSION)
    normalized.setdefault("session_bucket", session_bucket or session_bucket_at(created_at) or SESSION_BUCKET_UNKNOWN)
    normalized["primary_reason_code"] = primary
    normalized["secondary_reason_codes"] = secondary
    normalized.setdefault("input_missing_fields", _input_missing_fields(normalized))
    normalized.setdefault("comparison_mode", comparison_mode)
    normalized.setdefault("legacy_result", passed if legacy_result is None else legacy_result)
    normalized.setdefault("new_result", normalized.get("legacy_result") if new_result is None else new_result)
    normalized.setdefault("legacy_score", score if legacy_score is None else legacy_score)
    normalized.setdefault("new_score", normalized.get("legacy_score") if new_score is None else new_score)
    return normalized


def reason_code_fields(reason_codes: Iterable[Any] | None) -> dict[str, Any]:
    codes = normalize_reason_codes(reason_codes)
    return {
        "primary_reason_code": codes[0] if codes else "",
        "secondary_reason_codes": codes[1:],
    }


def _input_missing_fields(details: dict) -> list[str]:
    explicit = normalize_reason_codes(details.get("input_missing_fields") or [])
    if explicit:
        return explicit
    missing = []
    for value in details.get("insufficient_reason") or []:
        text = normalize_reason_code(value)
        lowered = text.lower()
        if "missing" in lowered or "insufficient" in lowered:
            missing.append(text)
    return normalize_reason_codes(missing)
