[CmdletBinding()]
param(
    [string]$ProjectRoot = "",
    [string]$DbPath = "",
    [string]$BindHost = "127.0.0.1",
    [int]$Port = 8000,
    [string]$Token = "",
    [switch]$EnableReconcileTrPilot,
    [switch]$EnableReconcileTrStartup,
    [switch]$ReconcileTrIncludeCash
)

$ErrorActionPreference = "Stop"
$Utf8Encoding = New-Object System.Text.UTF8Encoding -ArgumentList $false
[Console]::OutputEncoding = $Utf8Encoding
$OutputEncoding = $Utf8Encoding

if (-not $ProjectRoot) {
    $ProjectRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
} else {
    $ProjectRoot = Resolve-Path $ProjectRoot
}
$ProjectRoot = [string]$ProjectRoot

if (-not $DbPath) {
    $DbPath = Join-Path $ProjectRoot "data\trader.sqlite3"
}
$DbPath = [string](Resolve-Path $DbPath)

if (-not $Token) {
    $Token = if ($env:TRADING_CORE_TOKEN) { $env:TRADING_CORE_TOKEN } else { "local-dev-token" }
}

$Python64 = Join-Path $ProjectRoot "venv_64\Scripts\python.exe"
if (-not (Test-Path $Python64)) {
    $Python64 = "python"
}

$env:PYTHONIOENCODING = "utf-8"
$env:TRADING_CORE_TOKEN = $Token
$env:TRADING_DB_PATH = $DbPath

$env:TRADING_MODE = "OBSERVE"
$env:TRADING_ALLOW_LIVE = "0"
$env:TRADING_SEND_ORDER_ALLOWED = "false"
$env:TRADING_RUNTIME_ENABLED = "1"
$env:TRADING_RUNTIME_AUTO_START = "1"
$env:TRADING_RUNTIME_MODE = "OBSERVE"
$env:TRADING_RUNTIME_ALLOW_DRY_RUN_ORDERS = "0"
$env:TRADING_RUNTIME_ALLOW_LIVE_ORDERS = "0"
$env:STRATEGY_REBOOT_V2_ENABLED = "1"
$env:STRATEGY_RUNTIME_PROFILE = "THEME_CORE_V3"
$env:STRATEGY_REBOOT_V2_PROFILE = "THEME_CORE_V3"
$env:TRADING_OPENING_BURST_ENABLED = "1"
$env:TRADING_OPENING_BURST_CONFIGURED = "1"
$env:TRADING_OPENING_BURST_CATCH_UP_ENABLED = "1"
$env:TRADING_OPENING_BURST_OPT10032_MARKET_CODE = "000"
$env:TRADING_OPENING_BURST_OPT10032_INCLUDE_MANAGEMENT = "0"
$env:TRADING_OPENING_BURST_OPT10032_EXCHANGE_CODE = "3"
$env:TRADING_THEME_BOARD_ENABLED = "1"
$env:TRADING_THEME_CORE_V3_ENABLED = "1"
$env:TRADING_THEME_CORE_V3_USE_RUNTIME_MARKET_CONTEXT = "1"
$env:TRADING_THEME_CORE_V3_INGEST_CANDIDATES = "1"
$env:TRADING_THEME_EXPANSION_SUBSCRIPTIONS_ENABLED = "1"
$env:TRADING_STRATEGY_CONTEXT_V3_ENABLED = "1"
$env:TRADING_MARKET_REGIME_ENABLED = "1"
$env:TRADING_ENTRY_ENGINE_ENABLED = "1"
$env:TRADING_ENTRY_USE_STRATEGY_CONTEXT_V3 = "1"
$env:TRADING_ENTRY_ALLOW_LEGACY_THEME_CONTEXT_FALLBACK = "0"
$env:TRADING_SETUP_ROUTER_V3_ENABLED = "1"
$env:TRADING_SETUP_ROUTER_V3_OBSERVE_ONLY = "true"
$env:TRADING_SETUP_ROUTER_V3_INTERVAL_SEC = "1"
$env:TRADING_SETUP_ROUTER_V3_MAX_CANDIDATES_PER_CYCLE = "100"
$env:TRADING_SETUP_ROUTER_V3_PERIODIC_RECONCILE_SEC = "30"
$env:TRADING_SETUP_ROUTER_V3_MIN_COMPLETED_1M_CANDLES = "3"
$env:TRADING_SETUP_ROUTER_V3_SAVE_HISTORY = "true"
$env:TRADING_SETUP_ROUTER_READINESS_P01_ENABLED = "true"
$env:TRADING_SETUP_ROUTER_ATOMIC_READINESS_COMPLETION_ENABLED = "true"
$env:TRADING_SETUP_ROUTER_CANONICAL_MARKET_ACTION_ENABLED = "true"
$env:TRADING_MARKET_RS_SHADOW_ENABLED = "1"
$env:TRADING_MARKET_RS_SHADOW_INTERVAL_SEC = "30"
$env:TRADING_MARKET_RS_SHADOW_DEDUPE_SEC = "60"
$env:TRADING_MARKET_RS_SHADOW_MAX_PER_CYCLE = "50"
$env:TRADING_MARKET_RS_OUTCOME_ENABLED = "1"
$env:TRADING_MARKET_RS_OUTCOME_INTERVAL_SEC = "60"
$env:TRADING_MARKET_RS_OUTCOME_HORIZONS_SEC = "300,600,1200"
$env:TRADING_MARKET_RS_OUTCOME_MAX_BATCH_SIZE = "100"
$env:TRADING_POSITION_RISK_ENABLED = "1"
$env:TRADING_EXIT_ENGINE_ENABLED = "1"
$env:TRADING_MARKET_SIDE_PORTFOLIO_ENABLED = "1"
$env:TRADING_MARKET_SIDE_PORTFOLIO_OBSERVE_ONLY = "1"
$env:TRADING_MARKET_SIDE_PORTFOLIO_ENFORCE_BUY_LIMITS = "0"
$env:TRADING_ORDER_MANAGER_ENABLED = "0"
$env:TRADING_ORDER_MANAGER_OBSERVE_ONLY = "true"
$env:TRADING_ORDER_MANAGER_ENQUEUE_GATEWAY_COMMAND = "false"
$env:TRADING_ORDER_INTENT_ENABLED = "false"
$env:TRADING_ALLOW_LIVE_SIM_ORDERS = "0"
$env:TRADING_ENTRY_ALLOW_DRY_RUN_INTENTS = "0"
$env:TRADING_EXIT_ALLOW_DRY_RUN_SELL_INTENTS = "0"
$env:TRADING_RECONCILE_TR_SERVICE_ENABLED = "true"
$env:TRADING_RECONCILE_TR_DISPATCH_ENABLED = if ($EnableReconcileTrPilot) { "true" } else { "false" }
$env:TRADING_RECONCILE_TR_SIMULATION_ONLY = "true"
$env:TRADING_RECONCILE_TR_STARTUP_ENABLED = if ($EnableReconcileTrStartup) { "true" } else { "false" }
$env:TRADING_RECONCILE_TR_RECONNECT_ENABLED = "false"
$env:TRADING_RECONCILE_TR_PERIODIC_ENABLED = "false"
$env:TRADING_RECONCILE_TR_CASH_REQUIRED = if ($ReconcileTrIncludeCash) { "true" } else { "false" }
$env:TRADING_RECONCILE_TR_AUTO_HEAL_ENABLED = "false"
$env:TRADING_RECONCILE_TR_AUTO_CLEAR_STOP_NEW_BUY = "false"
$env:TRADING_DASHBOARD_V2_ENABLED = "1"
$env:TRADING_DASHBOARD_V2_AUTO_ROUTE = "1"
$env:TRADING_SHADOW_STRATEGY_OBSERVE_ONLY = "1"
$env:TRADING_SHADOW_STRATEGY_ALLOW_APPLY = "0"
$env:TRADING_CHANGE_PROPOSAL_ALLOW_AUTO_APPLY = "0"
$env:TRADING_STRATEGY_BASELINE_ENABLED = "true"
$env:TRADING_STRATEGY_BASELINE_ID = "leader_first_pullback_v1"
$env:TRADING_STRATEGY_BASELINE_VERSION = "1.0.0"
$env:TRADING_STRATEGY_BASELINE_FREEZE_ENABLED = "true"
$env:TRADING_STRATEGY_BASELINE_ALLOW_MUTATION = "false"
$env:TRADING_DAY_QUALIFICATION_ENABLED = "true"
$env:TRADING_DAY_QUALIFICATION_SAMPLE_INTERVAL_SEC = "30"
$env:TRADING_DAY_QUALIFICATION_WARMUP_GRACE_SEC = "180"
$env:TRADING_DAY_QUALIFICATION_MARKET_CONTEXT_UNAVAILABLE_MAX_RATE = "0.05"
$env:TRADING_DAY_QUALIFICATION_MARKET_CONTEXT_UNAVAILABLE_MAX_CONSECUTIVE = "3"
$env:TRADING_DAY_QUALIFICATION_FALLBACK_WARN_RATE = "0.10"
$env:TRADING_DAY_QUALIFICATION_FALLBACK_INVALID_RATE = "0.30"
$env:TRADING_DAY_QUALIFICATION_SUBSCRIPTION_WARN_COVERAGE = "0.90"
$env:TRADING_DAY_QUALIFICATION_SUBSCRIPTION_INVALID_COVERAGE = "0.70"
$env:TRADING_DAY_QUALIFICATION_FRESH_DATA_WARN_COVERAGE = "0.90"
$env:TRADING_DAY_QUALIFICATION_FRESH_DATA_INVALID_COVERAGE = "0.70"
$env:TRADING_CANDIDATE_FUNNEL_ENABLED = "true"
$env:TRADING_CANDIDATE_FUNNEL_SAVE_EPISODES = "true"
$env:TRADING_CANDIDATE_FUNNEL_STRICT_IDENTITY = "true"

$required = [ordered]@{
    TRADING_MODE = "OBSERVE"
    TRADING_ALLOW_LIVE = "0"
    TRADING_SEND_ORDER_ALLOWED = "false"
    TRADING_RUNTIME_MODE = "OBSERVE"
    TRADING_RUNTIME_ALLOW_DRY_RUN_ORDERS = "0"
    TRADING_RUNTIME_ALLOW_LIVE_ORDERS = "0"
    STRATEGY_REBOOT_V2_ENABLED = "1"
    STRATEGY_RUNTIME_PROFILE = "THEME_CORE_V3"
    STRATEGY_REBOOT_V2_PROFILE = "THEME_CORE_V3"
    TRADING_OPENING_BURST_ENABLED = "1"
    TRADING_OPENING_BURST_OPT10032_MARKET_CODE = "000"
    TRADING_OPENING_BURST_OPT10032_INCLUDE_MANAGEMENT = "0"
    TRADING_OPENING_BURST_OPT10032_EXCHANGE_CODE = "3"
    TRADING_THEME_BOARD_ENABLED = "1"
    TRADING_THEME_CORE_V3_ENABLED = "1"
    TRADING_THEME_CORE_V3_USE_RUNTIME_MARKET_CONTEXT = "1"
    TRADING_THEME_CORE_V3_INGEST_CANDIDATES = "1"
    TRADING_THEME_EXPANSION_SUBSCRIPTIONS_ENABLED = "1"
    TRADING_STRATEGY_CONTEXT_V3_ENABLED = "1"
    TRADING_MARKET_REGIME_ENABLED = "1"
    TRADING_ENTRY_ENGINE_ENABLED = "1"
    TRADING_ENTRY_USE_STRATEGY_CONTEXT_V3 = "1"
    TRADING_ENTRY_ALLOW_LEGACY_THEME_CONTEXT_FALLBACK = "0"
    TRADING_SETUP_ROUTER_V3_ENABLED = "1"
    TRADING_SETUP_ROUTER_V3_OBSERVE_ONLY = "true"
    TRADING_SETUP_ROUTER_V3_INTERVAL_SEC = "1"
    TRADING_SETUP_ROUTER_V3_MAX_CANDIDATES_PER_CYCLE = "100"
    TRADING_SETUP_ROUTER_V3_PERIODIC_RECONCILE_SEC = "30"
    TRADING_SETUP_ROUTER_V3_MIN_COMPLETED_1M_CANDLES = "3"
    TRADING_SETUP_ROUTER_V3_SAVE_HISTORY = "true"
    TRADING_SETUP_ROUTER_READINESS_P01_ENABLED = "true"
    TRADING_SETUP_ROUTER_ATOMIC_READINESS_COMPLETION_ENABLED = "true"
    TRADING_SETUP_ROUTER_CANONICAL_MARKET_ACTION_ENABLED = "true"
    TRADING_MARKET_RS_SHADOW_ENABLED = "1"
    TRADING_MARKET_RS_SHADOW_INTERVAL_SEC = "30"
    TRADING_MARKET_RS_SHADOW_DEDUPE_SEC = "60"
    TRADING_MARKET_RS_OUTCOME_ENABLED = "1"
    TRADING_MARKET_RS_OUTCOME_INTERVAL_SEC = "60"
    TRADING_MARKET_RS_OUTCOME_HORIZONS_SEC = "300,600,1200"
    TRADING_MARKET_RS_OUTCOME_MAX_BATCH_SIZE = "100"
    TRADING_POSITION_RISK_ENABLED = "1"
    TRADING_EXIT_ENGINE_ENABLED = "1"
    TRADING_MARKET_SIDE_PORTFOLIO_ENABLED = "1"
    TRADING_MARKET_SIDE_PORTFOLIO_OBSERVE_ONLY = "1"
    TRADING_MARKET_SIDE_PORTFOLIO_ENFORCE_BUY_LIMITS = "0"
    TRADING_ORDER_MANAGER_ENABLED = "0"
    TRADING_ORDER_MANAGER_OBSERVE_ONLY = "true"
    TRADING_ORDER_MANAGER_ENQUEUE_GATEWAY_COMMAND = "false"
    TRADING_ORDER_INTENT_ENABLED = "false"
    TRADING_ALLOW_LIVE_SIM_ORDERS = "0"
    TRADING_ENTRY_ALLOW_DRY_RUN_INTENTS = "0"
    TRADING_EXIT_ALLOW_DRY_RUN_SELL_INTENTS = "0"
    TRADING_RECONCILE_TR_SIMULATION_ONLY = "true"
    TRADING_RECONCILE_TR_AUTO_HEAL_ENABLED = "false"
    TRADING_RECONCILE_TR_AUTO_CLEAR_STOP_NEW_BUY = "false"
    TRADING_DASHBOARD_V2_ENABLED = "1"
    TRADING_DASHBOARD_V2_AUTO_ROUTE = "1"
    TRADING_STRATEGY_BASELINE_ENABLED = "true"
    TRADING_STRATEGY_BASELINE_ID = "leader_first_pullback_v1"
    TRADING_STRATEGY_BASELINE_VERSION = "1.0.0"
    TRADING_STRATEGY_BASELINE_FREEZE_ENABLED = "true"
    TRADING_STRATEGY_BASELINE_ALLOW_MUTATION = "false"
    TRADING_DAY_QUALIFICATION_ENABLED = "true"
    TRADING_DAY_QUALIFICATION_SAMPLE_INTERVAL_SEC = "30"
    TRADING_DAY_QUALIFICATION_WARMUP_GRACE_SEC = "180"
    TRADING_DAY_QUALIFICATION_MARKET_CONTEXT_UNAVAILABLE_MAX_RATE = "0.05"
    TRADING_DAY_QUALIFICATION_MARKET_CONTEXT_UNAVAILABLE_MAX_CONSECUTIVE = "3"
    TRADING_DAY_QUALIFICATION_FALLBACK_WARN_RATE = "0.10"
    TRADING_DAY_QUALIFICATION_FALLBACK_INVALID_RATE = "0.30"
    TRADING_DAY_QUALIFICATION_SUBSCRIPTION_WARN_COVERAGE = "0.90"
    TRADING_DAY_QUALIFICATION_SUBSCRIPTION_INVALID_COVERAGE = "0.70"
    TRADING_DAY_QUALIFICATION_FRESH_DATA_WARN_COVERAGE = "0.90"
    TRADING_DAY_QUALIFICATION_FRESH_DATA_INVALID_COVERAGE = "0.70"
    TRADING_CANDIDATE_FUNNEL_ENABLED = "true"
    TRADING_CANDIDATE_FUNNEL_SAVE_EPISODES = "true"
    TRADING_CANDIDATE_FUNNEL_STRICT_IDENTITY = "true"
}

Write-Host "Effective Reboot V2 OBSERVE configuration"
foreach ($key in $required.Keys) {
    $value = [Environment]::GetEnvironmentVariable($key)
    Write-Host ("  {0}={1}" -f $key, $value)
    if ($value -ne $required[$key]) {
        throw "Required flag mismatch: $key expected $($required[$key]) got $value"
    }
}
Write-Host ("  TRADING_DB_PATH={0}" -f $env:TRADING_DB_PATH)
Write-Host ("  Bind={0}:{1}" -f $BindHost, $Port)

Set-Location $ProjectRoot
& $Python64 -m uvicorn trading_app.api:app --host $BindHost --port $Port
